### ISSUE TITLE
Need some help understanding what meta.sh file is

### ISSUE THREAD

**Issue by JustLinuxUser** [PixelRifts/math-expr-evaluator#1]
Hi, I noticed a bunch of undocumented stuff:

1. the build scripts include UI?
2. there is a meta.sh and meta.bat files, they build something in source/opt/meta?
3. what is meta/gen_tables do?
4. why are there a bunch of includes in the source directory

My guess for all of this, is that u used another project as a base for this one, or I am a dumb dumb and you explained this in a previous video somewhere, also even if this is not supposed to be here, can you pls explain what is .mdesk file ext?

**Comment by PixelRifts** [comment]
Correct it's my [c-codebase](https://github.com/PixelRifts/c-codebase) which gives me a bunch of basic allocators and string helpers. The ui stuff should definitely go. The meta stuff is a metaprogram that generates some stuff like ui style stacks which are just tedious to implement by hand

**Comment by PixelRifts** [comment]
Only the source/expr folder has all the things related to math expression evaluation so you can check just that (and probably source/base for allocators and string util)
